version: "3.6"

services:

  jupyterlab:
    image: jupyter
    container_name: mk-jupyter
    ports:
      - 8888:8888
    volumes:
      #- shared-workspace:/home/jovyan/shared_workspace
      - ./:/home/jovyan/workspace

  spark-master:
    image: mk-spark-master
    container_name: mk-spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 8998:8998
    volumes:
      #- shared-workspace:/opt/workspace
      - ./:/home/jovyan/workspace

  spark-worker-1:
    image: mk-spark-worker
    container_name: mk-spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - ./:/home/jovyan/workspace
      #- shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  demo-database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres1234

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
